name: Build and Push Choinek Images

on:
   push:
      branches:
         - main
      paths:
         - '.github/workflows/build-choinek-images.yml'
         - 'ci-images/**'

jobs:
   build-and-push:
      runs-on: ubuntu-latest

      permissions:
         contents: read
         packages: write

      strategy:
         matrix:
            image:
               - {
                  source: "ci-images/php-scripts_8.4.Dockerfile",
                  image: "ci-images/php-scripts:8.4"
               }

      steps:
         -  name: Checkout Code
            uses: actions/checkout@v4

         -  name: Login to GitHub Container Registry
            uses: docker/login-action@v3
            with:
               registry: ghcr.io
               username: ${{ github.actor }}
               password: ${{ secrets.GITHUB_TOKEN }}

         -  name: Build Docker Image
            run: |
               docker build -f ${{ matrix.image.source }} -t ghcr.io/choinek/${{ matrix.image.image }} .

         -  name: Push Docker Image
            run: |
               docker push ghcr.io/choinek/${{ matrix.image.image }}

         # I used base64 to avoid issues with special characters in the output
         - name: Test Docker Image and Save Output
           run: |
              output=$(docker run --rm ghcr.io/choinek/${{ matrix.image.image }} php -v | base64)
              mkdir -p ci-images-info/$(dirname ${{ matrix.image.source }})
              outputFilePath=ci-images-info/${{ matrix.image.source }}.log
              echo "Source: ${{ matrix.image.source }}" > $outputFilePath
              echo "Image: ghcr.io/choinek/${{ matrix.image.image }}" >> $outputFilePath
              echo "Output:" >> $outputFilePath
              echo "$output" | base64 --decode >> $outputFilePath

         -  name: Upload Test Output as Artifact
            uses: actions/upload-artifact@v4
            with:
               name: test-outputs
               path: ci-images-info/

   commit-and-push:
      needs: build-and-push
      runs-on: ubuntu-latest
      steps:
         -  name: Checkout `Generated` Branch
            uses: actions/checkout@v4
            with:
               ref: generated

         -  name: Download Artifacts
            uses: actions/download-artifact@v3
            with:
               name: test-outputs

         -  name: Collect and Commit Updates to `generated` Branch
            run: |
               if [ -n "$(git status --porcelain)" ]; then
                 git config --global user.name "GitHub Actions"
                 git config --global user.email "actions@github.com"
                 git add ci-images-info/
                 git commit -m "Update ci-images test outputs automatically from build-choinek-images.yml"
               else
                 echo "No changes to commit."
               fi

         -  name: Push Updates
            run: |
               git push origin generated
