name: Deploy to GitHub Pages

on:
   push:
      branches:
         - main

jobs:
   deploy:
      runs-on: ubuntu-latest

      container:
         image: php:8.4-cli

      steps:
         -  name: Checkout Code
            uses: actions/checkout@v4

         -  name: Prepare .zip files
            run: ./action_gh_pages_prepare_zip_files.sh

         -  name: Generate JSON index
            run: php action_gh_pages_generate_index_json.php

         -  name: Generate HTML index page
            run: php action_gh_pages_generate_index_page.php

         -  name: Copy required files
            run: ./action_gh_pages_copy_required_files.sh

         - name: Deploy
           uses: peaceiris/actions-gh-pages@v4
           with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./public
