name: Deploy to GitHub Pages

on:
   push:
      branches:
         - main
      paths-ignore:
         - '.github/workflows/build-choinek-images.yml'
         - 'ci-images/**'
         - '.gitignore'
      workflow_dispatch:

jobs:
   deploy:
      runs-on: ubuntu-latest

      permissions:
         contents: write

      container:
         image: ghcr.io/choinek/ci-images/php-scripts:8.4

      steps:
         -  name: Checkout Code
            uses: actions/checkout@v4

         -  name: Copy required files
            run: .ach-repository-workflow/actions/action_gh_pages_copy_required_files.sh

         -  name: Prepare .zip files
            run: .ach-repository-workflow/actions/action_gh_pages_prepare_zip_script_groups.sh

         -  name: Generate JSON index
            run: php .ach-repository-workflow/actions/action_gh_pages_generate_index_json.php > public/index.json

         -  name: Generate HTML index page
            run: php .ach-repository-workflow/actions/action_gh_pages_generate_index_page.php > public/index.html

         - name: Deploy
           uses: peaceiris/actions-gh-pages@v4
           with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./public
